[phases.setup]
  nixPkgs = ['php81.withExtensions (pe: pe.enabled ++ [all.grpc])']

[phases.install]
cmds = ["mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx", "php -m", "composer install", "npm i", "cp .env.example .env", "php artisan optimize:clear"]
